window.ELECTION_DATA = {
  candidates: [
    { id:'lula', name:'Lula', party:'PT', color:'#20d040', photo:'/api/image?id=lula&v=7', focus:'42% 32%' },
    { id:'flavio', name:'Flávio Bolsonaro', party:'PL', color:'#ffd21c', photo:'/api/image?id=flavio&v=3', focus:'50% 12%' },
    { id:'renan', name:'Renan Santos', party:'Missão', color:'#1594ff', photo:'/api/image?id=renan&v=3', focus:'50% 10%' },
    { id:'caiado', name:'Ronaldo Caiado', party:'PSD', color:'#ff7a18', photo:'/api/image?id=caiado&v=3', focus:'50% 12%' },
    { id:'zema', name:'Romeu Zema', party:'Novo', color:'#a94cff', photo:'/api/image?id=zema&v=3', focus:'50% 10%' },
    { id:'cury', name:'Augusto Cury', party:'Avante', color:'#d9e1e8', photo:'/api/image?id=cury&v=3', focus:'50% 12%' },
    { id:'daciolo', name:'Cabo Daciolo', party:'Mobiliza', color:'#00b6ff', photo:'/api/image?id=daciolo&v=3', focus:'50% 10%' }
  ],
  polls: [
    {date:'2026-02-27',label:'27 fev',institute:'AtlasIntel/Bloomberg',scope:'Nacional',field:'fevereiro de 2026',publication:'27/02/2026',sample:'não informado',margin:'não informada',registry:'consultar TSE',source:'https://elpais.com/america/2026-02-27/bolsonaro-hijo-empata-con-lula-por-primera-vez-en-una-encuesta-electoral-en-brasil.html',values:{Lula:45,'Flávio Bolsonaro':39}},
    {date:'2026-03-03',label:'3 mar',institute:'Real Time Big Data',scope:'Nacional',field:'fim de fevereiro/início de março',publication:'03/03/2026',sample:'não informado',margin:'não informada',registry:'consultar TSE',source:'https://noticias.uol.com.br/ultimas-noticias/agencia-estado/2026/03/03/lula-tem-39-no-1-turno-e-flavio-bolsonaro-32-aponta-pesquisa-realtimebigdata.htm',values:{Lula:39,'Flávio Bolsonaro':32,'Renan Santos':2,'Romeu Zema':2}},
    {date:'2026-03-25',label:'25 mar',institute:'AtlasIntel/Bloomberg',scope:'Nacional',field:'março de 2026',publication:'25/03/2026',sample:'não informado',margin:'não informada',registry:'consultar TSE',source:'https://www.brasildefato.com.br/2026/03/25/atlasintel-lula-lidera-1o-turno-para-presidente-pela-primeira-vez-flavio-bolsonaro-aparece-a-frente-no-2o/',values:{Lula:45,'Flávio Bolsonaro':42.4}},
    {date:'2026-05-19',label:'19 mai',institute:'AtlasIntel/Bloomberg',scope:'Nacional',field:'maio de 2026',publication:'19/05/2026',sample:'não informado',margin:'não informada',registry:'consultar TSE',source:'https://www.cnnbrasil.com.br/eleicoes/atlas-lula-tem-47-das-intencoes-de-voto-no-1o-turno-flavio-343/',values:{Lula:47,'Flávio Bolsonaro':34.3}},
    {date:'2026-05-27',label:'27 mai',institute:'Indexa Pesquisas',scope:'Nacional',field:'maio de 2026',publication:'27/05/2026',sample:'não informado',margin:'não informada',registry:'consultar TSE',source:'https://www.jota.info/eleicoes/eleicoes-2026/lula-lidera-com-39-e-flavio-bolsonaro-tem-30-no-1o-turno-diz-indexa-pesquisas',values:{Lula:39,'Flávio Bolsonaro':30}},
    {date:'2026-07-01',label:'1 jul',institute:'AtlasIntel/Bloomberg',scope:'Nacional',field:'26 a 30/06/2026',publication:'01/07/2026',sample:'4.999',margin:'±1 p.p.',registry:'consultar TSE',source:'https://www.reuters.com/world/americas/lula-leads-senator-bolsonaro-brazil-presidential-run-off-poll-shows-2026-07-01/',values:{Lula:46.3,'Flávio Bolsonaro':36.6,'Renan Santos':7.8,'Ronaldo Caiado':2.9,'Romeu Zema':2}},
    {date:'2026-07-08',label:'8 jul',institute:'Meio/Ideia',scope:'Nacional',field:'3 a 6/07/2026',publication:'08/07/2026',sample:'1.500',margin:'±2,5 p.p.',registry:'consultar TSE',source:'https://www.cnnbrasil.com.br/eleicoes/meio-ideia-lula-tem-404-das-intencoes-de-voto-no-1o-turno-e-flavio-32/',values:{Lula:40.4,'Flávio Bolsonaro':32,'Renan Santos':5.4,'Ronaldo Caiado':4.2,'Romeu Zema':3.1,'Augusto Cury':1.8,'Cabo Daciolo':1.2}},
    {date:'2026-07-15',label:'15 jul',institute:'Genial/Quaest',scope:'Nacional',field:'10 a 13/07/2026',publication:'15/07/2026',sample:'2.004',margin:'±2 p.p.',registry:'consultar TSE',source:'https://noticias.r7.com/eleicoes/2026/genialquaest-lula-lidera-1-turno-com-40-dos-votos-flavio-bolsonaro-tem-28-15072026/',values:{Lula:40,'Flávio Bolsonaro':28,'Renan Santos':3,'Ronaldo Caiado':4,'Romeu Zema':2,'Augusto Cury':1,'Cabo Daciolo':1}},
    {date:'2026-07-16',label:'16 jul',institute:'PoderData/Aya',scope:'Nacional',field:'12 a 15/07/2026',publication:'16/07/2026',sample:'2.500',margin:'±2 p.p.',registry:'BR-00059/2026',source:'https://www.cnnbrasil.com.br/eleicoes/poderdata-aya-lula-tem-40-das-intencoes-de-voto-no-1a-turno-flavio-34/',values:{Lula:40,'Flávio Bolsonaro':34,'Renan Santos':6,'Ronaldo Caiado':4,'Romeu Zema':4,'Augusto Cury':3}},
    {date:'2026-07-21',label:'21 jul',institute:'Indexa Pesquisas',scope:'Nacional',field:'16 a 19/07/2026',publication:'21/07/2026',sample:'2.000',margin:'±2,2 p.p.',registry:'consultar TSE',source:'https://www.cnnbrasil.com.br/eleicoes/indexa-lula-tem-41-das-intencoes-de-voto-no-1o-turno-flavio-30/',values:{Lula:41,'Flávio Bolsonaro':30}},
    {date:'2026-07-24',label:'24 jul',institute:'Datafolha',scope:'Nacional',field:'22 a 24/07/2026',publication:'24/07/2026',sample:'2.004',margin:'±2 p.p.',registry:'consultar TSE',source:'https://www.reuters.com/world/americas/lula-leads-flavio-bolsonaro-brazil-election-poll-2026-07-24/',values:{Lula:40,'Flávio Bolsonaro':32,'Renan Santos':3,'Ronaldo Caiado':4,'Romeu Zema':3,'Augusto Cury':2,'Cabo Daciolo':1}},
    {date:'2026-07-27',label:'27 jul',institute:'Nexus/BTG',scope:'Nacional',field:'24 a 26/07/2026',publication:'27/07/2026',sample:'2.004',margin:'±2 p.p.',registry:'BR-01489/2026',source:'https://www.reuters.com/world/americas/brazils-lula-holds-lead-over-bolsonaro-btgnexus-election-poll-2026-07-27/',values:{Lula:42,'Flávio Bolsonaro':33,'Renan Santos':5,'Ronaldo Caiado':6,'Romeu Zema':3,'Augusto Cury':2,'Cabo Daciolo':1}}
  ],
  sourcesFallback: [
    {id:'tse',name:'TSE / PesqEle',kind:'Fonte oficial',coverage:['Nacional','Estadual','Municipal','Bairro'],online:true,url:'https://dadosabertos.tse.jus.br/dataset/pesquisas-eleitorais-2026'},
    {id:'datafolha',name:'Datafolha',kind:'Instituto',coverage:['Nacional','Estadual','Municipal'],online:true,url:'https://datafolha.folha.uol.com.br/'},
    {id:'quaest',name:'Quaest',kind:'Instituto',coverage:['Nacional','Estadual','Municipal'],online:true,url:'https://quaest.com.br/'},
    {id:'atlas',name:'AtlasIntel',kind:'Instituto',coverage:['Nacional','Estadual','Municipal'],online:true,url:'https://atlasintel.org/'},
    {id:'parana',name:'Paraná Pesquisas',kind:'Instituto',coverage:['Nacional','Estadual','Municipal'],online:true,url:'https://paranapesquisas.com.br/'},
    {id:'poderdata',name:'PoderData',kind:'Instituto',coverage:['Nacional','Estadual'],online:true,url:'https://www.poder360.com.br/poderdata/'},
    {id:'rtbd',name:'Real Time Big Data',kind:'Instituto',coverage:['Nacional','Estadual','Municipal'],online:true,url:'https://realtimebigdata.com.br/'},
    {id:'futura',name:'Futura',kind:'Instituto',coverage:['Nacional','Estadual','Municipal'],online:true,url:'https://futurapesquisa.com.br/'},
    {id:'ipespe',name:'Ipespe',kind:'Instituto',coverage:['Nacional','Estadual','Municipal'],online:true,url:'https://ipespe.org.br/'},
    {id:'gerp',name:'GERP',kind:'Instituto',coverage:['Nacional','Estadual','Municipal'],online:true,url:'https://www.gerp.com.br/'}
  ],
  ufs: ['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'],
  stateNames: {AC:'Acre',AL:'Alagoas',AP:'Amapá',AM:'Amazonas',BA:'Bahia',CE:'Ceará',DF:'Distrito Federal',ES:'Espírito Santo',GO:'Goiás',MA:'Maranhão',MT:'Mato Grosso',MS:'Mato Grosso do Sul',MG:'Minas Gerais',PA:'Pará',PB:'Paraíba',PR:'Paraná',PE:'Pernambuco',PI:'Piauí',RJ:'Rio de Janeiro',RN:'Rio Grande do Norte',RS:'Rio Grande do Sul',RO:'Rondônia',RR:'Roraima',SC:'Santa Catarina',SP:'São Paulo',SE:'Sergipe',TO:'Tocantins'},
  parties: [
    {name:'PT',color:'#e4252a',share:24},{name:'PL',color:'#1759a8',share:21},{name:'PSD',color:'#4b83c3',share:12},{name:'MDB',color:'#56a34b',share:10},{name:'UNIÃO',color:'#36a9e1',share:9},{name:'PP',color:'#0068a9',share:8},{name:'REPUBLICANOS',color:'#0b4f8a',share:7},{name:'OUTROS',color:'#6e7781',share:9}
  ]
};