window.ELECTION_DATA = {
  candidates: [
    { id:'lula', name:'Lula', party:'PT', initials:'LU', color:'#4aa8ff', photo:'/api/image?id=lula', credit:'https://commons.wikimedia.org/wiki/File:17.06.2025_-_Foto_Oficial_(54596867483).jpg' },
    { id:'flavio', name:'Flávio Bolsonaro', party:'PL', initials:'FB', color:'#ff6b6b', photo:'/api/image?id=flavio', credit:'https://commons.wikimedia.org/wiki/File:Fl%C3%A1vio_Bolsonaro_04_2026.jpg' },
    { id:'renan', name:'Renan Santos', party:'Missão', initials:'RS', color:'#f0b44d', photo:'/api/image?id=renan', credit:'https://commons.wikimedia.org/wiki/File:Renan_Santos.jpg' },
    { id:'caiado', name:'Ronaldo Caiado', party:'PSD', initials:'RC', color:'#35c98b', photo:'/api/image?id=caiado', credit:'https://commons.wikimedia.org/wiki/File:Foto_oficial_de_Ronaldo_Caiado.jpg' },
    { id:'zema', name:'Romeu Zema', party:'Novo', initials:'RZ', color:'#9f7aea', photo:'/api/image?id=zema', credit:'https://commons.wikimedia.org/wiki/File:Romeu_Zema_2025_(cropped).jpg' },
    { id:'cury', name:'Augusto Cury', party:'Avante', initials:'AC', color:'#22c1c3', photo:'/api/image?id=cury', credit:'https://commons.wikimedia.org/wiki/File:Augusto_Cury.jpg' },
    { id:'daciolo', name:'Cabo Daciolo', party:'Mobiliza', initials:'CD', color:'#ef7ab8', photo:'/api/image?id=daciolo', credit:'https://commons.wikimedia.org/wiki/File:Cabo_Daciolo_em_2022.jpg' }
  ],
  polls: [
    {date:'2026-02-27',label:'27 fev',institute:'AtlasIntel/Bloomberg',field:'fevereiro de 2026',publication:'27 fev 2026',sample:'não informado na fonte resumida',margin:'não informada na fonte resumida',registry:'consultar PesqEle/TSE',source:'https://elpais.com/america/2026-02-27/bolsonaro-hijo-empata-con-lula-por-primera-vez-en-una-encuesta-electoral-en-brasil.html',values:{Lula:45,'Flávio Bolsonaro':39}},
    {date:'2026-03-03',label:'3 mar',institute:'Real Time Big Data',field:'fim de fevereiro/início de março',publication:'3 mar 2026',sample:'não informado na fonte resumida',margin:'não informada na fonte resumida',registry:'consultar PesqEle/TSE',source:'https://noticias.uol.com.br/ultimas-noticias/agencia-estado/2026/03/03/lula-tem-39-no-1-turno-e-flavio-bolsonaro-32-aponta-pesquisa-realtimebigdata.htm',values:{Lula:39,'Flávio Bolsonaro':32,'Renan Santos':2,'Romeu Zema':2}},
    {date:'2026-03-25',label:'25 mar',institute:'AtlasIntel/Bloomberg',field:'março de 2026',publication:'25 mar 2026',sample:'não informado na fonte resumida',margin:'não informada na fonte resumida',registry:'consultar PesqEle/TSE',source:'https://www.brasildefato.com.br/2026/03/25/atlasintel-lula-lidera-1o-turno-para-presidente-pela-primeira-vez-flavio-bolsonaro-aparece-a-frente-no-2o/',values:{Lula:45,'Flávio Bolsonaro':42.4}},
    {date:'2026-05-19',label:'19 mai',institute:'AtlasIntel/Bloomberg',field:'maio de 2026',publication:'19 mai 2026',sample:'não informado na matéria',margin:'não informada na matéria',registry:'consultar PesqEle/TSE',source:'https://www.cnnbrasil.com.br/eleicoes/atlas-lula-tem-47-das-intencoes-de-voto-no-1o-turno-flavio-343/',values:{Lula:47,'Flávio Bolsonaro':34.3}},
    {date:'2026-05-27',label:'27 mai',institute:'Indexa Pesquisas',field:'maio de 2026',publication:'27 mai 2026',sample:'não informado na fonte resumida',margin:'não informada na fonte resumida',registry:'consultar PesqEle/TSE',source:'https://www.jota.info/eleicoes/eleicoes-2026/lula-lidera-com-39-e-flavio-bolsonaro-tem-30-no-1o-turno-diz-indexa-pesquisas',values:{Lula:39,'Flávio Bolsonaro':30}},
    {date:'2026-07-01',label:'1 jul',institute:'AtlasIntel/Bloomberg',field:'26 a 30 jun 2026',publication:'1 jul 2026',sample:'4.999',margin:'±1 p.p.',registry:'consultar PesqEle/TSE',source:'https://www.reuters.com/world/americas/lula-leads-senator-bolsonaro-brazil-presidential-run-off-poll-shows-2026-07-01/',values:{Lula:46.3,'Flávio Bolsonaro':36.6,'Renan Santos':7.8,'Ronaldo Caiado':2.9,'Romeu Zema':2}},
    {date:'2026-07-08',label:'8 jul',institute:'Meio/Ideia',field:'3 a 6 jul 2026',publication:'8 jul 2026',sample:'1.500',margin:'±2,5 p.p.',registry:'consultar PesqEle/TSE',source:'https://www.cnnbrasil.com.br/eleicoes/meio-ideia-lula-tem-404-das-intencoes-de-voto-no-1o-turno-e-flavio-32/',values:{Lula:40.4,'Flávio Bolsonaro':32,'Renan Santos':5.4,'Ronaldo Caiado':4.2,'Romeu Zema':3.1,'Augusto Cury':1.8,'Cabo Daciolo':1.2}},
    {date:'2026-07-15',label:'15 jul',institute:'Genial/Quaest',field:'10 a 13 jul 2026',publication:'15 jul 2026',sample:'2.004',margin:'±2 p.p.',registry:'consultar PesqEle/TSE',source:'https://noticias.r7.com/eleicoes/2026/genialquaest-lula-lidera-1-turno-com-40-dos-votos-flavio-bolsonaro-tem-28-15072026/',values:{Lula:40,'Flávio Bolsonaro':28,'Renan Santos':3,'Ronaldo Caiado':4,'Romeu Zema':2,'Augusto Cury':1,'Cabo Daciolo':1}},
    {date:'2026-07-16',label:'16 jul',institute:'PoderData/Aya',field:'12 a 15 jul 2026',publication:'16 jul 2026',sample:'2.500',margin:'±2 p.p.',registry:'BR-00059/2026',source:'https://www.cnnbrasil.com.br/eleicoes/poderdata-aya-lula-tem-40-das-intencoes-de-voto-no-1a-turno-flavio-34/',values:{Lula:40,'Flávio Bolsonaro':34,'Renan Santos':6,'Ronaldo Caiado':4,'Romeu Zema':4,'Augusto Cury':3}},
    {date:'2026-07-21',label:'21 jul',institute:'Indexa Pesquisas',field:'16 a 19 jul 2026',publication:'21 jul 2026',sample:'2.000',margin:'±2,2 p.p.',registry:'consultar PesqEle/TSE',source:'https://www.cnnbrasil.com.br/eleicoes/indexa-lula-tem-41-das-intencoes-de-voto-no-1o-turno-flavio-30/',values:{Lula:41,'Flávio Bolsonaro':30}},
    {date:'2026-07-24',label:'24 jul',institute:'Datafolha',field:'22 a 24 jul 2026',publication:'24 jul 2026',sample:'2.004',margin:'±2 p.p.',registry:'consultar PesqEle/TSE',source:'https://www.reuters.com/world/americas/lula-leads-flavio-bolsonaro-brazil-election-poll-2026-07-24/',values:{Lula:40,'Flávio Bolsonaro':32,'Renan Santos':3,'Ronaldo Caiado':4,'Romeu Zema':3,'Augusto Cury':2,'Cabo Daciolo':1}},
    {date:'2026-07-27',label:'27 jul',institute:'Nexus/BTG',field:'24 a 26 jul 2026',publication:'27 jul 2026',sample:'2.004',margin:'±2 p.p.',registry:'BR-01489/2026',source:'https://www.reuters.com/world/americas/brazils-lula-holds-lead-over-bolsonaro-btgnexus-election-poll-2026-07-27/',values:{Lula:42,'Flávio Bolsonaro':33,'Renan Santos':5,'Ronaldo Caiado':6,'Romeu Zema':3,'Augusto Cury':2,'Cabo Daciolo':1}}
  ]
};
